# CIS 2.2.1: Ensure that NGINX is run using a non-privileged, dedicated service account
user nginx;

worker_processes auto;
pid /var/run/nginx.pid;

# CIS 3.3: Ensure error logging is enabled and set to the info logging level
error_log /var/log/nginx/error.log info;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # CIS 2.5.1: Ensure server_tokens directive is set to off
    server_tokens off;

    # CIS 2.4.3: Ensure keepalive_timeout is 10 seconds or less, but not 0
    keepalive_timeout 10;

    # CIS 2.4.4: Ensure send_timeout is set to 10 seconds or less, but not 0
    send_timeout 10;

    # CIS 5.2.1: Ensure timeout values for reading the client header and body are set correctly
    client_body_timeout 10;
    client_header_timeout 10;

    # CIS 5.2.2: Ensure the maximum request body size is set correctly
    client_max_body_size 100K;

    # CIS 5.2.3: Ensure the maximum buffer size for URIs is defined
    large_client_header_buffers 2 1k;

    # CIS 5.2.4: Ensure the number of connections per IP address is limited
    limit_conn_zone $binary_remote_addr zone=limitperip:10m;

    # CIS 5.2.5: Ensure rate limits by IP address are set
    limit_req_zone $binary_remote_addr zone=ratelimit:10m rate=5r/s;

    # CIS 3.1: Ensure detailed logging is enabled
    log_format main 'Event Source Information Server Name: "$server_name" '
                    'Server Protocol: "$server_protocol" Hostname: "$hostname" Host: "$host" '
                    'Date and Timestamp Information Local Time: "$time_local" ISO8601 Time: "$time_iso8601" '
                    'Username Information Basic Authentication User: "$remote_user" '
                    'Source Address Information Source Address: Port: "$remote_addr:$remote_port" '
                    'Destination Address: Port "$server_addr:$server_port" '
                    'Request Information Request: "$request" HTTP Response Status: "$status" '
                    'Referer: "$http_referer" Content Type: "$content_type" Body Bytes Sent: "$body_bytes_sent" '
                    'User Agent: "$http_user_agent" ';

    # CIS 3.2: Ensure access logging is enabled
    access_log /var/log/nginx/access.log main;

    # CIS 2.4.2: Ensure requests for unknown host names are rejected (Default catch-all)
    server {
        listen 80 default_server;
        server_name _;
        
        # SKIPPED FOR TESTING:
        # listen 443 ssl http2 default_server;
        # ssl_certificate /etc/nginx/cert.pem;
        # ssl_certificate_key /etc/nginx/nginx.key;

        return 404;
    }

    include /etc/nginx/conf.d/*.conf;
}